groups:
- name: alertname
  rules:
  - alert: HighCpuRate
#   expr: job:request_latency_seconds:mean5m{job="myjob"} > 0.5 
    expr: node_cpu_seconds_total{cpu="0",mode="user"} > 7.0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: High cpu utilization
